export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_FAILURE = 'GET_HOTELS_FAILURE';
export const GET_HOTELS_REQUEST = 'GET_HOTELS_REQUEST';

export const GET_HOTEL_SUCCESS = 'GET_HOTEL_SUCCESS';


export const GET_HOTELS_DETAILS_SUCCESS = 'GET_HOTELS_DETAILS_SUCCESS';
export const GET_HOTELS_DETAILS_FAILURE = 'GET_HOTELS_DETAILS_FAILURE';
export const GET_HOTELS_DETAILS_REQUEST = 'GET_HOTELS_DETAILS_REQUEST';